mydjango/blogapp/urls.py
from django.urls import path
from blogapp import views

app_name = 'blogapp'

urlpatterns = [
    path('', views.PostListView.as_view(), name='list'),
    path('create', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/',views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/',views.PostDeleteView.as_view(), name='delete')
]

mydjango/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import AboutView, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),

    path('bookmark/', include('bookmarkapp.urls')),
    path('blog/', include('blogapp.urls')),
]

mydjango/blogapp/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='글 제목', max_length=30)
    context = models.TextField(verbose_name='글 내용')

    # 최초 저장시에만 수정되는 필드
    created_at = models.DateTimeField(verbose_name='작성시간', auto_now_add=True)
    # 수정할떄마다 갱신되는 필드
    updated_at = models.DateTimeField(verbose_name='수정시간', auto_now=True)

mydjango/blogapp/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'context']

mydjango/blogapp/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Post
from .forms import PostForm
from django.urls import reverse_lazy


class PostListView(ListView):
    # 1. 모델지정해주기
    model = Post
    # 2. 변수명
    context_object_name = 'post_list'
    # 3. templates 지정해주기 => 안해줄거임!(자동으로 지정됨)


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blogapp:list')


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'


class PostUpdateView(UpdateView):
    model = Post
    context_object_name = 'post_update'
    form_class = PostForm
    success_url = reverse_lazy('blogapp:list')


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blogapp:list')

mydjango/templates/blogapp/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %} 블로그 글 삭제{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col text-center">
            <h1>블로그 글 삭제</h1>

            <form method="post">
                {% csrf_token %}
                <p>블로그 글을 삭제하시겠습니까?</p>

                <input type="submit" value="네!" class="btn btn-primary">

            </form>
        </div>
    </div>
</div>
{% endblock %}


{% block footer %}
{% endblock%}

mydjango/templates/blogapp/post_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="row">
                <h1>{{ post.title }}</h1>
                <div class="col">
                    <p>{{post.context}}</p>
                <div>
                    <p>작성시간 : {{post.created_at}}</p>
                    <p>수정시간 : {{post.updated_at}}</p>
                </div>
                <a href={% url 'blogapp:update' post.id %} class="btn btn-primary">수정하기</a>
                <a href={% url 'blogapp:delete' post.id %} class="btn btn-primary">삭제하기</a>
            </div>

{% endblock %}

mydjango/templates/blogapp/post_form.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-11">
                    {% if post_update %}
                        <h1>블로그 글 수정하기</h1>
                    {% else %}
                        <h1>블로그 글 등록하기</h1>
                    {% endif %}
                </div>
                <div class="col">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="등록하기" class="btn btn-primary">
                    </form>
                </div>

{% endblock %}

mydjango/templates/blogapp/post_list.html
{% extends 'base.html' %}

{% block title %} 블로그 리스트{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-10">
                    <h1>My Blog</h1>
                </div>
                <div class="col-2 text-end float-right">
                    <a href="{% url 'blogapp:create' %}" class="btn btn-primary" >글 작성</a>
                    {% if post_list %}
                </div>
            </div>
        
                {% for post in post_list %}
                <div class="card" style="margin-bottom:10px; white-space: nowrap; overflow: hidden; text-overflow: clip;">
                    <div class="card-body">
                        <a href="{% url 'blogapp:detail' post.pk %}"><p class="card-title">{{post.title}}</p>
                        <p class="card-subtitle mb-10 text-muted">{{post.context}}</p>
                        </a>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>글이 작성되지 않았습니다!!!</p>
            {% endif %}
        </div>
            
        </div>
    </div>
</div>
{% endblock %}


{% block footer %}
{% endblock%}