mydjango/bookmarkapp/urls.py
from django.urls import path
from bookmarkapp import views


# 1. mysite/urls.py에서 복붙한다.
# 2. detail 페이지로 가서 url의 문제점을 얘기한다.
# 3. urls.py 돌아와서 name을 적어준다.

app_name = 'bookmarkapp'



urlpatterns = [
    # path('', views.bookmark_list,name='list'),
    # path('<int:pk>/', views.bookmark_detail, name='detail'),
    # path('create/', views.bookmark_create, name='create'),
    # path('update/<int:pk>/',views.bookmark_update, name='update'),
    # # path('<int:pk>/update/',views.bookmark_update, name='update'),

    # # localhost:8000/bookmark/10/update/
    # # localhost:8000/bookmark/update/10/
    # path('delete/<int:pk>/',views.bookmark_delete, name='delete'),

    path('new/', views.BookmarkListView.as_view(), name='list'),
    path('new/<int:pk>/', views.BookmarkDetailView.as_view(), name='detail'),
    path('new/create/', views.BookmarkCreateView.as_view(), name='create'),
    path('new/update/<int:pk>/', views.BookmarkUpdateView.as_view(), name='update'),
    path('new/delete/<int:pk>/', views.BookmarkDeleteView.as_view(), name='delete'),
    


]

# localhost:8000/bookmark/bookmark/

# 학교로 비교
# 2-1 ㅇㅇㅇ 2-2 ㅇㅇㅇ
# app_name = 'comment'
# localhost:8000/accounts/profile/update/1/ -> name='update'

mydjango/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import AboutView, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),

    path('bookmark/', include('bookmarkapp.urls')),
    path('blog/', include('blogapp.urls')),
]

mydjango/bookmarkapp/models.py
from django.db import models


class Bookmark(models.Model):
    title = models.CharField(verbose_name='북마크 이름', max_length=20)
    url = models.URLField(verbose_name='URL')
    memo = models.TextField(verbose_name='메모')

mydjango/bookmarkapp/forms.py
from django import forms
from .models import Bookmark


# 장고의 "꽃"
# - 빈 폼을 보여주는 역할
# - 폼을 통해 입력된 값을 검증하고 저장하는 역할

class BookmarkForm(forms.ModelForm):
    # title = forms.CharField()
    # url = forms.URLField()
    # memo = forms.CharField()


    # 어떤 모델과 어떤 필드들을 등록을 할거냐?를 알려줘야합니다.
    class Meta:
        model = Bookmark
        fields = ['title', 'url', 'memo']

mydjango/bookmarkapp/views.py
from django.shortcuts import redirect, render

from django.shortcuts import HttpResponse


def index(request):
    return HttpResponse('<h1>Hello World!</h1>')


# from bookmarks.models import Bookmark
# def bookmark_list(request):
#     bookmark_list = Bookmark.objects.all()
#     context = {'bookmark_list':bookmark_list}
#     return render(request, 'bookmark_list.html', context)


# def bookmark_detail(request, pk):
#     # bookmark = Bookmark.objects.get(id=pk)
#     bookmark = get_object_or_404(Bookmark, id=pk)

#     context = {'bookmark' : bookmark}
#     return render(request, 'bookmark_detail.html', context)


# from .forms import BookmarkForm
# def bookmark_create(request):
#     # if request.method == 'POST':
#     #     context = {'text':'POST METHOD!!!'}
#     #     return render(request, 'templates/bookmark_create.html', context)
#     # context={'text':'GET METHOD!!!'}    
#     # return render(request, 'templates/bookmark_create.html', context)
#     # bookmark = Bookmark()
#     # if request.method == 'POST':
#     #     bookmark.title = request.POST['title']
#     #     bookmark.url = request.POST['url']
#     #     bookmark.memo = request.POST['memo']

#     #     bookmark.save()

#     #     return redirect(f'/bookmark/{bookmark.id}/')
        
#     # return render(request, 'templates/bookmark_create.html')

#     # 사전형으로 html 파일에서 사용할 변수를 입력받기
#     # context = {}
#     # if request.method == 'POST':
#     #     form = BookmarkForm(request.POST or None)
#     #     if form.is_valid():
#     #         form.save()
#     #         return redirect(form)

#     context = {}
    
#     if request.method == 'POST':
#         form = BookmarkForm(request.POST)
#         if form.is_valid():
#             bookmark = form.save()
#             return redirect('bookmarks:detail', bookmark.id)
            
#     else:
#         form = BookmarkForm()
#         context['form']= form


#     return render(request, 'bookmark_create.html', context)


# from django.shortcuts import get_object_or_404
# def bookmark_update(request, pk):
#     # bookmark = Bookmark.objects.get(id=pk)
#     bookmark = get_object_or_404(Bookmark, id=pk)
#     # context={'bookmark':bookmark}

#     # if request.method == 'POST':
#     #     bookmark.title = request.POST['title']
#     #     bookmark.url = request.POST['url']
#     #     bookmark.memo = request.POST['memo']

#     #     bookmark.save()

#     #     return redirect(f'/bookmark/{bookmark.id}/')
        
#     # return render(request, 'templates/bookmark_update.html', context)


#     context = {}
    
#     if request.method == 'POST':
#         form = BookmarkForm(request.POST, instance=bookmark)
#         if form.is_valid():
#             bookmark = form.save()
#             return redirect('bookmarks:detail', bookmark.id)
            
#     else:
#         form = BookmarkForm(instance=bookmark)
#         context['form']= form


#     return render(request, 'templates/bookmark_update.html', context)





# def bookmark_delete(request, pk):
#     # bookmark = Bookmark.objects.get(id=pk)
#     bookmark = get_object_or_404(Bookmark, id=pk)

#     if request.method == 'POST':
#         bookmark.delete()
#         # return redirect('/bookmark/')
#         return redirect('bookmarks:list')

        
#     return render(request, 'templates/bookmark_delete.html')




from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

# class BookmarkListView(ListView):
#     model = Bookmark
#     # 적지 않으면 object_list 라는 변수명으로 접근해야함
#     # context_object_name = 'bookmark_list'
#     template_name = 'bookmark_list.html'


# class BookmarkDetailView(DetailView):
#     model = Bookmark
#     context_object_name = 'bookmark'
#     template_name = 'bookmark_detail.html'


# from django.urls import reverse_lazy
# class BookmarkCreateView(CreateView):
#     model = Bookmark
#     form_class = BookmarkForm
#     success_url = reverse_lazy('bookmarks:list')
#     # template_name = 'bookmark_create.html'

# class BookmarkUpdateView(UpdateView):
#     model = Bookmark
#     form_class = BookmarkForm
#     success_url = reverse_lazy('bookmarks:list')
#     # template_name = 'bookmark_update.html'
#     context_object_name = 'bookmark'


# class BookmarkDeleteView(DeleteView):
#     model = Bookmark


from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .models import Bookmark
from .forms import BookmarkForm
class BookmarkListView(ListView):
    # 1. model정하기
    model = Bookmark
    
    # 2. html파일에서 사용할 변수명 정하기
    context_object_name = 'bookmark_list'

    # 3. 어떤 templates(html)와 연결해줄지 정하기
    # template_name = 'bookmark_list.html'

    # BASE_DIR/templates/bookmark_list.html

    # BASE_DIR/templates/bookmarks/bookmark_list.html



class BookmarkDetailView(DetailView):
    model = Bookmark
    context_object_name = 'bookmark'
    # template_name = 'bookmark_detail.html'


from django.urls import reverse_lazy
class BookmarkCreateView(CreateView):
    model = Bookmark
    form_class = BookmarkForm
    success_url = reverse_lazy('bookmarks:list')
    # template_name = 'bookmark_create.html'


class BookmarkUpdateView(UpdateView):
    model = Bookmark
    context_object_name = 'bookmark'
    form_class = BookmarkForm
    success_url = reverse_lazy('bookmarks:list')
    # template_name = 'bookmark_update.html'


class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmarks:list')
    # template_name = 'bookmark_delete.html'

mydjango/templates/bookmarkapp/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title %} 북마크 삭제 페이지 {% endblock %}

{% block content %}

    <h1>북마크 삭제_새로 만듦</h1>

    <form method="post">
        {% csrf_token %}
        <p>북마크를 삭제하시겠습니까?</p>

        <input type="submit" value="네!">

    </form>
{% endblock %}

mydjango/templates/bookmarkapp/bookmark_detail.html
{% extends 'base.html' %}
{% block title %} 북마크 리스트 페이지 {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
    <h1>{{ bookmark.title }}</h1>
    <ul>
        <li>URL : <a href="{{ bookmark.url }}">{{ bookmark.url }}</a></li>
        <li>memo : {{ bookmark.memo }}</li>
    </ul>
    {% comment %} {% comment %} <a href="/bookmark/update/{{ bookmark.id }}/">수정하기</a> {% endcomment %}
    <a href="{% url 'bookmarkapp:update' bookmark.id %}">수정하기</a>
    
    
    
    {% comment %} <a href="/bookmark/delete/{{ bookmark.id }}/">삭제하기</a> {% endcomment %}
    <a href="{% url 'bookmarkapp:delete' bookmark.id %}">삭제하기</a>
</div>
</div>
</div>
{% endblock %}

mydjango/templates/bookmarkapp/bookmark_form.html
{% extends 'base.html' %}
{% block title %} 북마크 리스트 페이지 {% endblock %}

{% block content %}
<div class="text-center">
    {% if bookmark %}
        <h1>북마크 수정하기_새로 만들었음</h1>
    {% else %}
        <h1>북마크 등록하기_새로 만들었음</h1>
    {% endif %}
    <form method="post">
        {% csrf_token %}

        {% comment %} <input type="text" name="title" placeholder="북마크 제목">
        <input type="text" name="url" placeholder="북마크 url">
        <input type="text" name="memo" placeholder="북마크 메모"> {% endcomment %}

        {{ form.as_p }}

        <input type="submit" value="북마크 등록">
    </form>


    {% comment %} <form method="post">
        {% csrf_token %}
        <input type="submit" value="포스트 요청 보내기">
    </form> {% endcomment %}
</div>
{% endblock %}

mydjango/templates/bookmarkapp/bookmark_list.html
{% extends 'base.html' %}
{% block title %} 북마크 리스트 페이지 {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
    <h1>북마크 리스트</h1>
    <ul>
        {% if bookmark_list %}
        {% comment %} {{ bookmark_list }} {% endcomment %}
            {% for i in bookmark_list %}
                <li><a href="{% url 'bookmarkapp:detail' i.id %}">{{ i.title }}</a></li>
            {% endfor %}
        {% else %}
            <p>북마크가 작성되지 않았습니다!</p>
        {% endif %}

    </ul>
    <!-- 2. 과제(북마크 만들기 링크생성) -->
    <a href="{% url 'bookmarkapp:create' %}">북마크 만들기</a>
</div>
</div>
</div>
{% endblock %}