mydjango/blogapp/urls.py
from django.urls import path
from blogapp import views

app_name = 'blogapp'

urlpatterns = [
    path('', views.PostListView.as_view(), name='list'),
    path('create', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/',views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/',views.PostDeleteView.as_view(), name='delete')
]

mydjango/bookmarkapp/urls.py
from django.urls import path
from bookmarkapp import views


# 1. mysite/urls.py에서 복붙한다.
# 2. detail 페이지로 가서 url의 문제점을 얘기한다.
# 3. urls.py 돌아와서 name을 적어준다.

app_name = 'bookmarkapp'



urlpatterns = [
    # path('', views.bookmark_list,name='list'),
    # path('<int:pk>/', views.bookmark_detail, name='detail'),
    # path('create/', views.bookmark_create, name='create'),
    # path('update/<int:pk>/',views.bookmark_update, name='update'),
    # # path('<int:pk>/update/',views.bookmark_update, name='update'),

    # # localhost:8000/bookmark/10/update/
    # # localhost:8000/bookmark/update/10/
    # path('delete/<int:pk>/',views.bookmark_delete, name='delete'),

    path('new/', views.BookmarkListView.as_view(), name='list'),
    path('new/<int:pk>/', views.BookmarkDetailView.as_view(), name='detail'),
    path('new/create/', views.BookmarkCreateView.as_view(), name='create'),
    path('new/update/<int:pk>/', views.BookmarkUpdateView.as_view(), name='update'),
    path('new/delete/<int:pk>/', views.BookmarkDeleteView.as_view(), name='delete'),
    


]

# localhost:8000/bookmark/bookmark/

# 학교로 비교
# 2-1 ㅇㅇㅇ 2-2 ㅇㅇㅇ
# app_name = 'comment'
# localhost:8000/accounts/profile/update/1/ -> name='update'

mydjango/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import AboutView, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),

    path('bookmark/', include('bookmarkapp.urls')),
    path('blog/', include('blogapp.urls')),
]

mydjango/templates/about.html
{% extends 'base.html' %}
{% block title %} about 페이지 {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col text-center">
            <h1>👩‍💻만든사람👩‍💻 : 김혜원</h1>
            <p>이용한 기술 - Django, Bootstrap</p>
            <p>코드 : <a href="https://github.com/OhyunIt2022/kimhyewon">@heyoni</a></p>
            <p>깃헙 페이지 : <a href="https://github.com/heyoni/">@heyoni</a></p>


        </div>
    </div>
</div>
{% endblock %}
    

mydjango/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            MySite
          </a>
    
          <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
            <li><a href="{% url 'bookmarkapp:list' %}" class="nav-link px-2 link-dark">Bookmark</a></li>
            <li><a href="{% url 'blogapp:list' %}" class="nav-link px-2 link-dark">Blog</a></li>
            <li><a href="/about/" class="nav-link px-2 link-dark">About</a></li>
          </ul>
    
          <div class="col-md-3 text-end">
            <button type="button" class="btn btn-outline-primary me-2">Login</button>
            <button type="button" class="btn btn-primary">Sign-up</button>
          </div>
        </header>
    </div>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    {% block content %}{% endblock %}
    
    {% block footer %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

mydjango/templates/home.html
{% extends 'base.html' %}
{% block title %} 홈페이지 {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col text-center">
            <h1>내 장고 프로젝트의 첫 페이지입니다.</h1>

        </div>
    </div>
</div>
{% endblock %}
    